# Basic
title: KiShing
subtitle: 个人博客
description: Minecraft
# 头像里面的标题
avatarTitle: KiShing
# 头像里面的描述
avatarDesc: CTF
url: "https://Linsjc.github.io"

# 博客是否自动生成目录，false为不生成
enableToc: true

# Comment
comment:
    # livere:  # https://www.livere.com
    # disqus: 
    # uyan:  # 有言id,登录有言官网申请

# Social
social:
    weibo: 6992107863
    github: Linsjc
    # zhihu: 
    # juejin: 
    # jianshu: 
    # twitter:
    mail: 2926218539@qq.com


# 百度统计
# 使用博客模板请去掉或者更换 id
baidu:
    id: 9a8f427c59b50b2fae2e3ccbd856b2c3

permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}
    - {title: 标签, description: tags, url: '/tags'}
    - {title: 技术支持, description: support, url: '/support'}
    - {title: 关于我, description: about, url: '/about'}


# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"
